language: node_js
sudo: false
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1

matrix:
  fast_finish: true
  include:
    - node_js: "6"
      os: linux
      env: SCRIPT=lint
    - node_js: "6"
      os: linux
      env: SCRIPT=test
    - node_js: "6"
      os: osx
      env: SCRIPT=test

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
